[workspace]
authors = ["Dan Olds <dolds@bnl.gov>"]
channels = ["conda-forge"]
name = "SimDAT2D"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
numpy = ">=2.2.5,<3"
pandas = ">=2.2.3,<3"
matplotlib = ">=3.10.3,<4"
scikit-learn = ">=1.6.1,<2"
dash = ">=3.0.4,<4"
plotly = ">=6.1.0,<7"
dask = ">=2025.5.0,<2026"
ipython = ">=9.2.0,<10"
pyfai = ">=2025.3.0,<2026"
jupyter = ">=1.1.1,<2"
notebook = ">=7.4.2,<8"
ipykernel = ">=6.29.5,<7"
pip = ">=25.1.1,<26"
